//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module.Testing.Nunit.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Module.Testing.Nunit.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;cardCode&quot;:&quot;054-000-598&quot;,
        ///&quot;cardType&quot;:&quot;investprojectco&quot;,
        ///&quot;fields&quot;:[
        ///{&quot;fieldName&quot;:&quot;StateId&quot;,&quot;value&quot;:&quot;0. Выявление потребности (до А1)&quot;,&quot;valueId&quot;:830,&quot;dataTypeCode&quot;:6}
        ///,
        ///{&quot;fieldName&quot;:&quot;Name&quot;,&quot;value&quot;:&quot;89789&quot;,&quot;valueId&quot;:&quot;89789&quot;,&quot;dataTypeCode&quot;:5}
        ///,
        ///{&quot;fieldName&quot;:&quot;ProjectCo1DepartmentId&quot;,&quot;value&quot;:&quot;Проекты нового бизнеса&quot;,&quot;valueId&quot;:4,&quot;dataTypeCode&quot;:6}
        ///,
        ///{&quot;fieldName&quot;:&quot;ProjectCo2DepartmentId&quot;,&quot;value&quot;:&quot;СиТ&quot;,&quot;valueId&quot;:18,&quot;dataTypeCode&quot;:6}
        ///,
        ///{&quot;fieldName&quot;:&quot;ProjectDepartmentCfo2Id&quot;,&quot;value&quot;:&quot;REIN&quot;,&quot;valueId&quot;:309,&quot;da [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SetFieldsError1 {
            get {
                return ResourceManager.GetString("SetFieldsError1", resourceCulture);
            }
        }
    }
}
